### PR TITLE
Project housekeeping

### PR DESCRIPTION
**Pull request by f00f**
Cleaned up some ugly project config details

### CODE REVIEW

**Comment by jangernert** [comment]
@sisiplac told me the AstraSDK is obsolete and right now only the OpenNI implementation is used. BUT there is already a new SDK in the pipeline that potentially has a completely new API.

**Comment by f00f** [comment]
OK, then I'll remove that project from MC2, too.

**Comment by f00f** [comment]
Alright, that's it from my side. Ready for review and merge.

**Comment by f00f** [comment]
ping @mischastik

**Pull request merged**
