### PR TITLE
Update WindowsTargetPlatformVersion to 10.0.15063.0

### PR DESCRIPTION
**Pull request by f00f**

### CODE REVIEW

**Comment by sisiplac** [comment]
Any feedback on my question?

**Comment by f00f** [comment]
I don't think it has any effect, but I'm not an expert on that topic and have not made an in-depth research yet

**Comment by f00f** [comment]
Wikipedia says that Windows SDK for Windows 8.1 and Windows SDK for Windows 10 both did not remove any features, so I guess we should be safe.

**Comment by sisiplac** [comment]
Ok - then it should be fine!

**Pull request merged**
