### PR TITLE
Fixed output path and removed NET STD incompatible resource files

### PR DESCRIPTION
**Pull request by sisiplac**

### CODE REVIEW

**Comment by f00f** [comment]
I have fixed and cleaned up stuff. I hope everything is working now.
Should be merged quickly as it fixes the current build issues of master.

**Comment by jangernert** [comment]
I can confirm that the branch now at least compiles fine.
I'll have a look at the code now.

**Comment by jangernert** [comment]
So `MetriCam2.Cameras.RealSense2` is now built as AnyCPU? But you still have to have the correct version of `realsense2.dll` to accompany it.
Just tested the the binaries with MetriCalibrate_Intrinsics and everything seems to be in order.

**Comment by f00f** [comment]
@sisiplac: can we talk about @jangernert's AnyCPU question tomorrow? I'm also interested in that.

**Pull request merged**
