### PR TITLE
Release 16.0

### PR DESCRIPTION
**Pull request by sisiplac**
Please merge #225 before merging this PR!

### CODE REVIEW

**Comment by f00f** [comment]
I rebased onto `master` after merging #225 

I didn't trust the Github web ui to do "the right thing" (TM)

**Comment by f00f** [comment]
Should we indicate, in the ChangeLog, which nuget packages are public?

Maybe even add this info to the readme (prob. out of scope).

**Comment by sisiplac** [comment]
> Should we indicate, in the ChangeLog, which nuget packages are public?
> 
> Maybe even add this info to the readme (prob. out of scope).

Yes, very good idea - we should mention it both in the Readme and in the Changelog! The Readme seems to be out-of-date anyway. The `libraries` section can be removed completely, and due to `DirectoryBuild.{props,targets}` the minimum required VS version is 2017 instead of 2012. I would't mind if we have a separate commit for that within this branch.

**Comment by sisiplac** [comment]
The restructuring of the `Readme` is really great - so please merge after rewording/squashing/ordering the commits.

**Pull request merged**
